# This is a basic workflow to help you get started with Actions

name: Linting, Testing, Building and Deploying

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [ opened, synchronize, reopened ] # this actions are default
    branches: [ "main" ]  # this is the target branch
  push:
    branches:
      - main  # this syntax is the same as above
      # - develop
      # - hotfix/*  --> hotfix/new hotfix/old
      # - hotfix/** --> hotfix/new/new hotfix/old/old
    ## you may only define one of `paths` and `paths-ignore` for a single event
    # paths:
    #   - "./" # this is the path to the files that will trigger the workflow
    # paths-ignore:
    #   - ".github/workflows/*" # this is the path to the files that will be ignored

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Linting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci
        
      - name: Lint Code
        run: npm run lint

  Testing:
    needs: Linting
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:ci

  Building:
    needs: Testing
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      output_js_file_name: ${{ steps.PublishJsFileName.outputs.js_file_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Code
        run: npm run build

      - name: Publish Js file name
        id: PublishJsFileName
        run: find dist/assets/*.js -type f -execdir echo 'js_file_name={}' >> $GITHUB_OUTPUT  ';'

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  Deploying:
    needs: Building
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          # path: dist

      - name: Output Build artifacts
        run: ls

      - name: Output values (job outputs)
        run: echo ${{ needs.Building.outputs.output_js_file_name }}

      - name: Deploy
        run: echo "Deploying Project"

