name: Reusable
on: 
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: 'Name of the person to greet'
        required: true
        default: 'World'

jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name : Output message
        run: |
          echo "Hello ${{ inputs.artifact-name }}!"

