name: Reusable
on: workflow_call

jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name : Output message
        uses: echo "Heelo World"
